title: 케이팝 얼굴상 테스트
email: mun_1201@naver.com
description: 인공지능을 이용한 케이팝 소속사 얼굴상 테스트
disqus_shortname: moony01
google_analytics: G-J7NNCSLXY2
# avatar_url: /static/img/ico.jpg
url: "https://moony01.com"
baseurl: "/kpopface" # the subpath of your site, e.g. /blog
twitter_username: mun01180
github_username:  moony01

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - lambda